permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 刘明聪
  email: 710733615@qq.com
  link: http://onion-liu.github.io/
  weibo: http://weibo.com/mingcongliu
  github: https://github.com/onion-liu/

# 站点信息
title: Onion的博客 
description: Onion的博客
url: http://onion-liu.github.io/
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7nj0p2.com1.z0.glb.clouddn.com/gh-avatar.jpg
favicon: http://7nj0p2.com1.z0.glb.clouddn.com/gh-avatar.jpg

# google analytics 设置
#ga:
#  id: UA-54767140-1
#  url: yansu.org

# disqus 设置
#disqus:
#  shortname: suyan-zh