# Site settings
title: Peace of Mind
email: ray050899@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Peace of Mind
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ruixmizzou.com" # the base hostname & protocol for your site
rss_url: /pages/feed.xml

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'

# Social account
twitter:
# weibo:    ID
github: ray2928
# codepen:  username
# dribbble: username

# avatar头像及Favicon
avatar: https://www.gravatar.com/avatar/8d8b0c9229031c71143ca42027d81249
favicon: https://www.gravatar.com/avatar/8d8b0c9229031c71143ca42027d81249

# disqus 设置
disqus:
  shortname: ray2928

# google analytics 设置
ga:
  id: #google-analytics id
  url: ruixmizzou.com

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
sass:
  style: compressed
